# Laboratory Task 5

NumPy & PyTorch Tensor Operations
Perform Standard Imports


Create set_seed() Function: Accepts seed: int as a parameter to set the random seed.

Create NumPy Array arr: Contains 6 random integers between 0 (inclusive) and 5 (exclusive) using seed 42.

Create Tensor x: Convert arr into a PyTorch tensor.

Change dtype: Convert x from int32 to int64.

Reshape x: Reshape x into a
 tensor.

Extract Column: Return the right-hand column of tensor x.

Square Values: Return a tensor of square values of x without mutating x.

Create Tensor y: Generate a tensor with the same number of elements as x (6 elements) using PyTorch with random integers between 0 and 5 (seed 42), shaped appropriately to allow matrix multiplication
.

Matrix Multiplication: Compute the matrix product of x and y.

In [ ]:
import numpy as np
import torch

def set_seed(seed: int):
    np.random.seed(seed)
    torch.manual_seed(seed)

set_seed(42)

# Create NumPy Array arr (6 random integers between 0 and 5)
arr = np.random.randint(0, 5, size=6)
print("NumPy Array (arr):\n", arr)

# Create Tensor x from arr
x = torch.from_numpy(arr)
print("\nInitial Tensor x:\n", x)
print("Initial dtype:", x.dtype)

# Change dtype from int32 to int64
x = x.to(torch.int64)
print("\nTensor x after dtype conversion:\n", x)
print("Updated dtype:", x.dtype)

# Reshape x into a 3x2 tensor (inferred from context)
x = x.reshape(3, 2)
print("\nReshaped Tensor x (3x2):\n", x)

# Extract Column (Right-hand column)
right_column = x[:, 1]
print("\nRight-hand column of x:\n", right_column)

# Square Values without mutating x
x_squared = x.pow(2)
print("\nSquared Tensor (x_squared):\n", x_squared)
print("Original Tensor x (unmutated):\n", x)

# Create Tensor y for matrix multiplication (2x3 shape, inferred from context)
y = torch.randint(0, 5, (2, 3), dtype=torch.int64)
print("\nTensor y (2x3):\n", y)

# Matrix Multiplication (x @ y)
matrix_prod = torch.matmul(x, y)
print("\nMatrix Product of x and y (3x3):\n", matrix_prod)

NumPy Array (arr):
 [3 4 2 4 4 1]

Initial Tensor x:
 tensor([3, 4, 2, 4, 4, 1])
Initial dtype: torch.int64

Tensor x after dtype conversion:
 tensor([3, 4, 2, 4, 4, 1])
Updated dtype: torch.int64

Reshaped Tensor x (3x2):
 tensor([[3, 4],
        [2, 4],
        [4, 1]])

Right-hand column of x:
 tensor([4, 4, 1])

Squared Tensor (x_squared):
 tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])
Original Tensor x (unmutated):
 tensor([[3, 4],
        [2, 4],
        [4, 1]])

Tensor y (2x3):
 tensor([[2, 2, 1],
        [4, 1, 0]])

Matrix Product of x and y (3x3):
 tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])


**Key Takeaways**

Tensor manipulation across NumPy and PyTorch forms the core foundation for data preparation and custom model layers. Converting a NumPy array into a PyTorch tensor shares underlying memory pointers when using torch.from_numpy(), which means data transformations require careful type management like explicit .to(torch.int64) casting. Operations like reshaping via .reshape() or .view() alter structural dimensions without changing the underlying numerical elements. When executing matrix multiplication ($x \cdot y$), dimensional compatibility strictly requires the inner matrix dimensions to match (e.g., matching the columns of $x$ to the rows of $y$), producing an output matrix bounded by their outer dimensions.